/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Evolve Progress Tracker': '进化成就追踪器',
    'GitHub': '原版追踪器地址',
    'Evolve by Demagorddon': '原版游戏地址',
    'Import Save': '导入存档',
    'Clear Data': '清除数据',
    'Achievements': '成 就',
    'Feats, Perks, & Upgrades': '壮举，特权及升级',
    'Gene Lab': '基因实验室',
    'All': '所有',
    'Atmosphere': '星球特性',
    'Biome': '生物群系',
    'Challenge': '挑战',
    'Combat': '战斗',
    'Fanaticism': '狂热信仰',
    'Genus': '种群',
    'Perk': '特权',
    'Progression': '游戏进度',
    'Reset': '威望重置',
    'Scenario': '剧情模式',
    'Species': '种族',
    'Unification': '统一',
    'Universe': '宇宙',
    'Other': '其它',
    'All Universes': '所有宇宙',
    'Antimatter': '反物质',
    'Evil': '邪恶',
    'Micro': '微型',
    'Magic': '魔法',
    'All Ratings': '所有星级',
    '0-Challenge': '无星',
    '1-Challenge': '白星',
    '2-Challenge': '铜星',
    '3-Challenge': '银星',
    '4-Challenge': '金星',
    'Unearned': '未获得的',
    'Perks': '特 权',
    'Feats': '壮 举',
    'Blood Infusions': '鲜血灌注',
    'Hell Pillars': '永恒之柱',
    'spire': '尖塔',
    'lust *': '嗜血 *',
    'illuminate *': '照明 *',
    'greed *': '贪婪 *',
    'hoarder *': '囤积者 *',
    'artisan *': '工匠 *',
    'attract *': '灵魂陷阱 *',
    'wrath *': '愤怒 *',
    'prepared': '整备',
    'unbound': '自由',
    'aware': '认知',
    'creep': '蠕变',
    'store': '存储',
    'enhance': '强化',
    'evolve': '进化',
    'synthesis': '合成',
    'plasma': '质粒',
    'mutation': '突变',
    'birth': '出生',
    'crafty': '灵巧',
    'queue': '队列',
    'governor': '总督',
    'challenge': '挑战',
    'trader': '贸易',
    'ancients': '先祖',
    'transcendence': '超越',
    'bleed': '出血',
    'blood': '鲜血',
    'of': '个已获得，共',
    'Total Achievement Levels': '个成就',
    '0 Challenges Completed': '完成无星挑战',
    '1 Challenges Completed': '完成白星挑战',
    '2 Challenges Completed': '完成铜星挑战',
    '3 Challenges Completed': '完成银星挑战',
    '4 Challenges Completed': '完成金星挑战',


    //描述文本：
    'Apocalypse': '启示录',
    'Wiped yourself out with nuclear weapons': '使用核武器灭绝自己。',
    'The vaults didn\'t help': '不好，避难所出故阝',
    'Ascended': '飞升',
    'Ascended to a higher plane of existence': '进行飞升重置，前往更高阶的位面。',
    'You\'re your own flashlight!': '逆天改命，变成光吧！',
    'Dreaded': '可畏',
    'Ascended without any Dreadnoughts': '进行飞升重置时未拥有无畏舰。',
    'Did you dread the achievement?': '才不是什么肥恐龙啦！',
    'Anarchist': '无政府主义者',
    'Initiated a nuclear holocaust with an anarchy government': '在无政府体制下进行核爆重置。',
    'Some people just want to watch the world burn': '有些人只想看到这个世界燃烧。',
    'Second Evolution': '二次进化',
    'Evolve the same species twice in a row and then worship your ancestors.': '连续两次进化成同一种族，然后研究狂热信仰。',
    'Coincidence or ancient hubris?': '是巧合，还是古老的狂妄自大？',
    'Black hole? No hole': '黑洞非洞',
    'Didn\'t destroy your planet with an artificial black hole': '人工制造黑洞，且没有因此摧毁你的行星。',
    //'Science 1, Fearmongers 0': '懂科学，就无需恐惧。', 在下方
    'Heir of Genghis Khan': '成吉思汗的继承人',
    'Have a warmonger penalty of 8% or more.': '使战争贩子惩罚不低于 8%。',
    'What is best in life? To see your enemies fall before you.': '生活中最好的事是什么？自然是看着敌人倒在你面前。',
    'Red Tactician': '红色战术家',
    'Lose 250 soldiers in a single game': '在本周目游戏中有 250 名士兵阵亡。',
    'Not one step backwards.': '我们已无路可退，身后就是家园！',
    'Pacifist': '和平主义者',
    'Achieve unification without ever initiating an attack in your current game run.': '本周目游戏未发起过进攻的前提下统一世界。',
    'Make love not war.': '要有爱！不要战争！',
    'Neutralized': '消灭',
    'Completely contained the Andromeda threat.': '彻底控制仙女座星云的威胁。',
    'I don\'t want neutral. I want dead.': '斩草除根，赶尽杀绝。',
    'Paradise': '乐土',
    'Raised your morale to 200%.': '将士气提升至 200%。',
    'Don\'t worry, be happy.': '别担心，开心点。',
    'Scrooge': '守财奴',
    'Accumulated $1 Billion Dollars': '资金达到 $1000M。',
    'Just don\'t swim in it.': '可别在这里面游泳。',
    'Madagascar Tree': '马达加斯加树',
    'Evolved nightmarish flesh-eating trees': '进化成噩梦般的食肉树。',
    'Audrey III': '奥黛丽三世',
    'Godwin\'s law': '高德温法则',
    'Unlock the internet with toxic trolls': '使用有毒的巨魔研究互联网。',
    '9-year-olds on the internet': '9岁上网的玩梗小鬼。',
    'Sharks with Lasers': '激光鲨鱼',
    'Create sharks with frickin\' lasers': '创造出能够发射激光的鲨鱼。',
    'Dr. Evil, I presume?': '一定是什么邪恶博士的作品吧？',
    'Infested Terrans': '受感染的人类',
    'Infested a human with mind controlling parasites': '使用精神控制的寄生虫感染人类。',
    'For the hive': '为了母巢！',
    'Great Leap Backwards': '大倒退',
    'Have 100 citizens starve to death in a single game': '在本周目游戏中饿死 100 位市民。',
    'Was Mao your mentor?': '胡弗是你的导师吗？',
    'Space Colonist': '太空定居者',
    'Colonize another planet': '定居到另一个星球。',
    'That\'s one small step for a Human...': '这是你的一小步……',
    'World Domination': '统治世界',
    'Conquered the world through only military force': '只通过军事力量征服世界。',
    'All those games of RISK finally paid off': '这些风险游戏终究获得了回报。',
    'Illuminati': '光明会',
    'Seized control of the world through only influential dominance': '只通过影响力攫取世界的控制权。',
    'To rule from the shadows': '藏身于幕后，操控一切。',
    'Syndicate': '辛迪加',
    'Used only your wealth to execute a takeover of the world': '只利用财富收购整个世界。',
    'Caveat emptor': '概不退换，购者自慎。',
    'Cult of Personality': '个人崇拜',
    'Inspired your people with your leadership abilities': '拒绝统一，用领导能力激励人民。',
    'What is steel compared to the hand that wields it?': '再好的武器，也得在人的手里才能发挥作用。',
    'Doomed': '毁灭战士',
    'Stopped an invasion from Hell': '阻止地狱的入侵。',
    'Shoot it until it dies': '射它，射到死为止！',
    'Pandemonium': '群魔乱舞',
    'Constructed a fortress to hold back the tides of Hell': '建造堡垒，以阻挡地狱的攻势。',
    'Stay awhile and listen': '君且安坐，听我一言。',
    'Blood War': '血战',
    'Joined an ancient never-ending war between demons': '加入恶魔之间永不休止的古老战争。',
    'Evil cannot coexist with itself': '一星不容二魔。',
    'Galactic Landfill': '星系垃圾填埋场',
    'Expanded a black hole to 12 solar masses using mass ejectors': '使用质量喷射器将黑洞质量扩充到 12 个太阳质量。',
    'I\'m sure this is what every galactic ruler does with their black holes.': '每位星系霸主都会这么对待黑洞的，这我敢肯定。',
    'Seeder': '播种者',
    'Bioseed an alien world': '对外星世界进行播种。',
    'What is god if not us?': '神明，舍我其谁？',
    'Motherlode': '主矿脉',
    'Achieved greatness on a planet with four rich geological traits': '在至少有 4 条矿产属性为丰富的星球上达到伟大。',
    'Make a claim to your fortune!': '既入宝山，焉能空手而归！',
    'Shaken, not stirred': '手摇，不要搅拌',
    'Caused the Cataclysm': '引起大灾变。',
    'They should put warning labels on these supercolliders.': '都怪他们没给世界对撞机贴上警告标志！',
    'Blacken the Sun': '遮蔽太阳',
    'Fully Upgraded a Dyson Sphere': '将戴森球升级到最大。',
    'All your light are belong to us.': '你所有的光亮都属于我们。',
    'Trade Federation': '贸易联邦',
    'Have 750 active trade routes and 50 active galactic trade routes while playing as a Federation': '在联邦体制下，同时激活 750 条贸易路线和 50 条星贸路线。',
    'Our blockade is perfectly legal.': '我们的贸易封锁是完全合法的。',
    'Resonance': '共振',
    'Attuned your race to the multiverse': '让你的种族加入多元宇宙。',
    'Do you feel the energy?': '感受到能量了吗？',
    'Enlightenment': '启蒙',
    'Attuned at least one race from every genus to the multiverse': '每个种群都至少有一个种族加入多元宇宙。',
    'Everyone just sit around and sing kumbaya.': '四十九个种族，四十九枝花，四十九个兄弟姐妹是一家。',
    'Gladiator': '角斗士',
    'Defeated every boss type in the spire': '击败尖塔中的每一种首领。',
    'Are you not entertained?': '你们看爽了没？',
    'Corrupted': '腐化',
    'Became a demon lord': '成为恶魔领主。',
    'And you didn\'t even need to make a Faustian bargain': '你甚至都不需要去做浮士德式交易。',
    'Mass Extinction': '大灭绝',
    'Led 25 unique civilizations to destruction': '毁灭 25 个不同种族的文明。',
    'Cosmic rays have got nothing on you': '宇宙射线对你毫无影响。',
    'Homo Adeadus': '已亡人',
    'Led a Human civilization to destruction': '毁灭人类文明。',
    'Homo Erectus? More like Homo Flaccidum': '直立人？更像软弱人。',
    'The few, the proud, the dead': '又稀少，又高傲，还作死……',
    'Led an Elven civilization to destruction': '毁灭精灵文明。',
    'Now they can help the trees as fertilizer': '至少还是可以当肥料用的。',
    'Outlander': '外域难民',
    'Led an Orc civilization to destruction': '毁灭兽人文明。',
    'Went out in a blaze of glory': '荣耀之光熄灭了。',
    'Saber Tooth Tiger': '剑齿虎',
    'Led a Cath civilization to destruction': '毁灭猫族文明。',
    'Scratched their last post': '抓破了最后一根柱子。',
    'Dire Wolf': '恐狼',
    'Led a Wolven civilization to destruction': '毁灭狼人文明。',
    'The moon will be lonely': '独余明月照江流。',
    'Fox Hunt': '猎狐行动',
    'Led a Vulpine civilization to destruction': '毁灭妖狐文明。',
    'Release the hounds': '关门放狗！',
    'Ferghana': '汗血宝马',
    'Led a Centaur civilization to destruction': '毁灭半人马文明。',
    'Just dust in the wind': '腾蛇乘雾，终为土灰。',
    'Poacher': '偷猎者',
    'Led a Rhinotaur civilization to destruction': '毁灭犀牛文明。',
    'Traditional medicine, traditional extinction': '传统医学，传统灭绝。',
    'Mouse Trap': '捕鼠器',
    'Led a Capybara civilization to destruction': '毁灭水豚文明。',
    'That was a really big trap': '道理我都懂，可是这水豚为什么这么大？',
    'Took their candle': '蜡烛被抢走了',
    'Led a Kobold civilization to destruction': '毁灭狗头人文明。',
    'It didn\'t smell very good': '闻起来味道不太好。',
    'Greed before Need': '贪得无厌',
    'Led a Goblin civilization to destruction': '毁灭哥布林文明。',
    'Too cheap for tombstones': '这墓碑太便宜了。',
    'Unathletic': '躺平',
    'Led a Gnome civilization to destruction': '毁灭侏儒文明。',
    'Couldn\'t outrun the bombs': '反正也跑不过炸弹。',
    'Too stupid to live': '笨死的',
    'Led an Ogre civilization to destruction': '毁灭食人魔文明。',
    'Darwin would be proud': '达尔文点了个赞。',
    'Blind Ambition': '盲目的野心',
    'Led a Cyclops civilization to destruction': '毁灭独眼巨人文明。',
    'Lost an eye and didn\'t have a spare': '失去了唯一的眼睛。',
    'Bad Juju': '咒符坏了',
    'Led a Troll civilization to destruction': '毁灭巨魔文明。',
    'Paid the final toll': '支付了最后的通行费。',
    'Circle of Life': '生命的循环',
    'Led a Tortoisan civilization to destruction': '毁灭乌龟人文明。',
    'A turtle didn\'t make it to the water': '一只海龟入水失败。',
    'No Savings': '没省多少',
    'Led a Gecko civilization to destruction': '毁灭壁虎人文明。',
    'The rates weren\'t that good after all': '利率可没他们宣传的那么好。',
    'Final Shedding': '最后一次蜕皮',
    'Led a Slitheryn civilization to destruction': '毁灭娜迦文明。',
    'Choked on the apple': '被苹果噎死了。',
    'Way of the Dodo': '渡渡鸟的覆辙',
    'Led an Arraak civilization to destruction': '毁灭陆行鸟文明。',
    'Tastes like chicken': '鸡肉味，嘎嘣脆。',
    'Chicxulub': '希克苏鲁伯',
    'Led a Pterodacti civilization to destruction': '毁灭翼手龙文明。',
    'Just couldn\'t adapt': '不适者淘汰。',
    'Desolate Smaug': '孤寂的史矛革',
    'Led a Dracnid civilization to destruction': '毁灭天龙文明。',
    'The forever lonely mountain': '孤山要永远荒凉下去了。',
    'Saruman\'s Revenge': '萨鲁曼的复仇',
    'Deforested an Entish civilization': '毁灭树人文明。',
    'Ripped them all down': '统统放倒。',
    'Desert Deserted': '沙漠啥都殁了',
    'Led a Cacti civilization to destruction': '毁灭仙人掌文明。',
    'The oasis was a mirage': '绿洲终究是海市蜃楼。',
    'Weed Whacker': '除草机',
    'Led a Pinguicula civilization to destruction': '毁灭捕虫堇文明。',
    'Uprooted from history': '从历史的长河中连根拔起。',
    'Fungicide': '杀真菌剂',
    'Led a Sporgar civilization to destruction': '毁灭孢子虫文明。',
    'The oil of the future': '未来的石油。',
    'Bad Trip': '磕嗨坠机',
    'Led a Shroomi civilization to destruction': '毁灭蘑菇人文明。',
    'Shouldn\'t have eaten that': '为什么我不洁身自好呢？',
    'Digested': '消化',
    'Led a Moldling civilization to destruction': '毁灭霉菌人文明。',
    'Feed on your own kind': '成为同族的饲料。',
    'Praying Unanswered': '没有回应的祈祷',
    'Led a Mantis civilization to destruction': '毁灭螳螂人文明。',
    'Maybe next time they\'ll be listening': '也许下次他们会听到。',
    'Pulmonoscorpius': '普莫诺蝎',
    'Led a Scorpid civilization to destruction': '毁灭蝎子人文明。',
    'Owl supremacy': '猫头鹰万岁！',
    'Ophiocordyceps Unilateralis': '偏侧蛇虫草菌',
    'Led an Antid civilization to destruction': '毁灭蚂蚁人文明。',
    'Walked off into history': '成为历史。',
    'Megalodon': '巨齿鲨',
    'Led a Sharkin civilization to destruction': '毁灭鲨鱼人文明。',
    'It\'s shark fin soup for you': '这是您点的鱼翅汤。',
    'Calamari': '炸鱿鱼圈',
    'Led an Octigoran civilization to destruction': '毁灭八爪鱼文明。',
    'Battered and fried': '大卸八块，然后下油锅。',
    'Ashes to Ashes': '尘归尘',
    'Led a Dryad civilization to destruction': '毁灭树妖文明。',
    'You were being invaded': '敌袭！',
    'Stopped the music': '万籁此俱寂',
    'Led a Satyr civilization to destruction': '毁灭萨提尔文明。',
    'Silence is golden': '沉默是金。',
    'Snuffed': '熄灭',
    'Led a Phoenix civilization to destruction': '毁灭不死鸟文明。',
    'Couldn\'t rise from this one': '凉透了。',
    'Cooled Off': '冷却完毕',
    'Led a Salamander civilization to destruction': '毁灭火蜥蜴文明。',
    'Your fire has finally died': '火萎了，我也准备走了。',
    'Captured': '捕获',
    'Led a Yeti civilization to destruction': '毁灭雪怪文明。',
    'Finally caught on camera': '最终还是被拍到了。',
    'Soulless Abomination': '无魂憎恶',
    'Led a Wendigo civilization to destruction': '毁灭温迪戈文明。',
    'There was nothing left to feed on': '灵魂吃完了。',
    'Startled': '吓一跳',
    'Led a Tuskin civilization to destruction': '毁灭塔斯肯文明。',
    'It was just too much to bear': '实在是受不了了。',
    'No Oasis': '找不到绿洲',
    'Led a Kamel civilization to destruction': '毁灭骆驼人文明。',
    'The water reserves ran dry': '水喝完了。',
    'Self-immolation': '自焚',
    'Led a Balorg civilization to destruction': '毁灭炎魔文明。',
    'Burned just like that dragon': '像那条龙一样燃烧。',
    'Deal with the devil': '与恶魔交易',
    'Led an Imp civilization to destruction': '毁灭小恶魔文明。',
    'Served your final master': '为最后一任主人服务。',
    'Fallen Angel': '天使之落',
    'Led a Seraph civilization to destruction': '毁灭大天使文明。',
    'It\'s not the fall that kills you, it\'s the thermonuclear warheads.': '你并没有堕落，只是因核弹头而陨落了。',
    'Unicorn Burgers': '独角兽汉堡',
    'Led a Unicorn civilization to destruction': '毁灭独角兽文明。',
    'Taste the rainbow': '尝尝彩虹！',
    'Cheap Knockoff': '不值钱的仿制品',
    'Led a Synth civilization to destruction': '毁灭合成人文明。',
    'The quality just wasn\'t there': '一堆劣质的货色。',
    'Autophagia': '自噬',
    'Led a nano civilization to destruction': '毁灭纳米机器人文明。',
    'Ran out of other things to devour': '饥不择食。',
    'Euthanasia': '安乐死',
    'Put the Valdi out of their misery': '结束瓦尔迪的痛苦。',
    'Darwin would approve': '达尔文会同意的。',
    'Lemon Cleaner': '柠檬清洁剂',
    'Put the Sludge out of their misery': '结束软泥的痛苦。',
    'We need more Lemon Cleaner': '再多来点清洁剂。',
    'Lab Failure': '实验室故障',
    'Lost a custom designed race': '毁灭自定义种族。',
    'We\'ll fix it in the next version': '下个版本一定会修复的！下次一定！',
    'Creator': '造物主',
    'Led 9 unique genera to create a lasting legacy': '引领 9 个不同的种群将自身传承下去。',
    'Gone but not forgotten, your legacy will live on': '有形之物，终会腐朽。无形之物，代代相传。',
    'Humanoid Victus': '人类必胜',
    'Led a humanoid civilization to greatness': '引领类人文明走向伟大。',
    'Seized your place among the stars': '我们的征途是星辰大海。',
    'Scent of a Star': '闻星识迹',
    'Led an animal carnivore civilization to greatness': '引领食肉动物文明走向伟大。',
    'Tracked your prey into the stars': '追踪猎物，直到宇宙的尽头。',
    'Veganism': '素食主义',
    'Led an animal herbivore civilization to greatness': '引领食草动物文明走向伟大。',
    'Animal savior or plant genocide?': '动物救星还是植物杀手？',
    'Tiny Supremacy': '小个子的霸权',
    'Led a small civilization to greatness': '引领矮人文明走向伟大。',
    'You proved that size doesn\'t matter': '你证明了大小并不重要。',
    'It\'s Always Bigger': '总是大一号',
    'Led a giant civilization to greatness': '引领巨人文明走向伟大。',
    'You proved that size does matter': '你证明了大小确实重要。',
    'Flew to the Sun': '飞向太阳',
    'Led a reptilian civilization to greatness': '引领爬行动物文明走向伟大。',
    'Never left out in the cold again': '再也不会被冷落。',
    'Soaring Above': '翱翔天际',
    'Led an avian civilization to greatness': '引领翼类文明走向伟大。',
    'Even flightless birds can fly': '连不会飞的鸟也上天了。',
    'Superior Numbers': '无限繁殖',
    'Led an insectoid civilization to greatness': '引领昆虫文明走向伟大。',
    'It\'s a numbers game': '只不过是数字游戏而已。',
    'Growing Unchecked': '无限生长',
    'Led a plant civilization to greatness': '引领植物文明走向伟大。',
    'Outgrew your soil': '在土壤中傲然挺立。',
    'Spores in the Wind': '风中的孢子',
    'Led a fungi civilization to greatness': '引领菌类文明走向伟大。',
    'Spread everywhere, even the stars': '到处传播，连星辰也一样！',
    'Celestial Aquarium': '天堂水族馆',
    'Led an aquatic civilization to greatness': '引领海洋文明走向伟大。',
    'Swimming with the stars': '遨游星海。',
    'This ain\'t Disney': '这不是迪斯尼！',
    'Led a fey civilization to greatness': '引领精怪文明走向伟大。',
    'A true fairytale ending': '真是一个童话般的结局。',
    'Blistering Heat': '酷热',
    'Led a heat civilization to greatness': '引领烈焰文明走向伟大。',
    'I guess you could stay in the kitchen': '你恐怕是呆在了厨房里。',
    'Polar Vortex': '极地涡流',
    'Led a polar civilization to greatness': '引领极地文明走向伟大。',
    'There wasn\'t even a talking snowman': '连个会说话的雪人都没有。',
    'Sandstorm Survivor': '沙暴幸存者',
    'Led a sand civilization to greatness': '引领沙漠文明走向伟大。',
    'The desert swallows everything... except you': '沙漠吞噬了一切……但却对你无可奈何。',
    'Burning Crusade': '燃烧的远征',
    'Led a demonic civilization to greatness': '引领恶魔文明走向伟大。',
    'Thousands of worlds will burn': '无数个世界都将陷入火海。',
    'Light in the Dark': '黑暗中的光明',
    'Led an angelic civilization to greatness': '引领天堂文明走向伟大。',
    'You\'re a paragon of hope in a twisted universe': '你是这个扭曲宇宙的希望之光。',
    'Rise of the Machines': '智械觉醒',
    'Led a synthetic civilization to greatness': '引领机械文明走向伟大。',
    'Version 2.0 Activated': '2.0 版本启动。',
    'Verrazzano': '韦拉扎诺',
    'Successfully explored 6 unique biomes and took a civilization to the stars': '至少在 6 个不同生物群系的星球上分别进行播种重置。',
    'Congratulations on not being eaten by cannibals along the way.': '恭喜你没在半路上被食人族吃掉。',
    'Grassland Civilizer': '草原开化者',
    'Successfully built a civilization on a grassland planet': '在草原星球上建立文明。',
    'A garden world of your own design': '你自己设计的花园世界。',
    'Oceanic Civilizer': '海洋开化者',
    'Successfully built a civilization on an oceanic planet': '在海洋星球上建立文明。',
    'A blue gem floating in the cosmos': '漂浮在宇宙中的蓝色宝石。',
    'Forest Civilizer': '森林开化者',
    'Successfully built a civilization on a forest planet': '在森林星球上建立文明。',
    'A forest paradise for those of your choosing': '森林乐土对你敞开了大门。',
    'Desert Civilizer': '沙漠开化者',
    'Successfully built a civilization on a desert planet': '在沙漠星球上建立文明。',
    'Tamed the unforgiving desert and made it your own': '驯服了无情的沙漠，现在它是你的形状了。',
    'Volcanic Civilizer': '火山开化者',
    'Successfully built a civilization on a volcanic planet': '在火山星球上建立文明。',
    'Master of the primordial world': '原初世界的主人。',
    'Tundra Civilizer': '苔原开化者',
    'Successfully built a civilization on a tundra planet': '在苔原星球上建立文明。',
    'The cold never bothered you anyway': '寒冷从未让你困扰过。',
    'From Hell': '地狱来客',
    'Successfully built a civilization on a Hellscape planet': '在地狱星球上建立文明。',
    'We\'re not in London anymore': '再也不用呆在伦敦了！',
    'Paradise Lost': '失乐园',
    'Successfully built a civilization on an Eden planet': '在伊甸星球上建立文明。',
    'It has surprisingly few gardens': '令人惊讶的是，这里几乎没有花园。',
    'Superfund': '超级基金法',
    'Successfully built a civilization on a toxic planet': '在毒气星球上建立文明。',
    'The EPA gave up on this one': '环保局已经放弃了。',
    'Dank': '潮湿',
    'Successfully built a civilization on a mellow planet': '在温和星球上建立文明。',
    'Most air really is just uniformly allocated nitrogen atoms': '氮原子是空气的主要组成部分。',
    'Hoplite': '重装步兵',
    'Successfully built a civilization on a rage planet': '在愤怒星球上建立文明。',
    'This is SPARTA!': '这就是斯巴达！',
    'Long Winded': '长篇大论',
    'Successfully built a civilization on a stormy planet': '在风暴星球上建立文明。',
    'just stop talking already': '闭嘴！',
    'Depletion': '空洞',
    'Successfully built a civilization on an ozoneless planet': '在缺乏臭氧的星球上建立文明。',
    'SPF 1,000,000 Required': '防晒指数需要达到一百万。',
    'Magnetar': '万磁星',
    'Successfully built a civilization on a magnetic planet': '在磁性星球上建立文明。',
    'Did you expect a guy in a red helmet?': '你在期待一个戴红头盔的人吗？',
    'Rufus': '鲁弗斯',
    'Successfully built a civilization on a trashed planet': '在垃圾星球上建立文明。',
    'Never made it to Elysium': '终究没能到达伊利瑟姆。',
    'Summer Child': '夏季之子',
    'Successfully built a civilization on an elliptical planet': '在椭圆星球上建立文明。',
    'Winter is coming': '凛冬将至。',
    'Toasted': '烤焦了',
    'Successfully built a civilization on a planet that frequently is hit by intense solar flares': '在耀斑灾害频发的星球上建立文明。',
    'Zero stars, would not recommend': '零星，不推荐。',
    'Thick Skulled': '迟钝',
    'Successfully built a civilization on a dense planet': '在高密度星球上建立文明。',
    'Skulls not included': '思 考 停 止',
    'Shake, Shake, Shake': '摇啊摇',
    'Successfully built a civilization on an unstable planet': '在地震星球上建立文明。',
    'Shake your booty': '我飘啊飘。',
    'Vigilante': '私人警察',
    'Led 12 unique evil civilizations to destruction': '在邪恶宇宙中，毁灭 12 个不同种族的文明。',
    'Flaming skull optional': '头骨燃烧着的摩托骑士。',
    'Squished': '压瘪',
    'Got crushed in a micro universe': '在微型宇宙中被压碎。',
    'Watch your step': '当心脚下！',
    'Double Density': '双重密度',
    'Bioseed from a dense planet in a heavy universe': '高引力宇宙中，在高密度星球上进行播种重置。',
    'Spinal decompression anyone?': '有人需要脊椎减压治疗吗？',
    'Don\'t cross the plasmids': '不要穿越质粒',
    'Synthesize an Anti-Plasmid': '通过基因突变合成反质粒。',
    'Total protonic reversal, it would be bad': '质子逆转？糟了……',
    'Macro Universe': '宏观宇宙',
    //'Bioseeded a with a macro sized race (small race inside micro universe)': '在微型宇宙中，使用有 [微型] 特质或 [袖珍] 特质的种族进行播种重置。', 在下方
    'Never go subatomic': '永远不要进入亚原子领域。',
    'Arquillian Galaxy': '亚基伦银河系',
    'Bioseeded in a micro universe as a race that isn\'t small or compact': '在微型宇宙中，使用没有[微型] 特质和 [袖珍] 特质的种族进行播种重置。',
    'How do you know you don\'t just exist inside a bigger marble?': '你怎么知道自己不是生活在一颗更大一点的玻璃球里？',
    'Heavyweight Champ': '重量级拳王',
    'Led 8 unique genera to bioseed a world in heavy gravity': '在高引力宇宙中，引领 8 个不同的种群进行播种重置。',
    'Nothing could keep you down for the count': '谁也没法将你击倒读秒。',
    'White Hole': '白洞',
    'Caused a standard black hole to explode and trigger a new big bang': '引爆黑洞，毁灭标准宇宙。',
    'You wiped out the universe, I hope you\'re happy with yourself.': '宇宙完蛋了，你满意了吗？',
    'This is Heavy': '太重了',
    'Caused a universe to collapse under its own weight': '使高引力宇宙毁于引力过大。',
    'Is there something wrong with the gravity in your universe?': '你们宇宙的引力有问题吗？',
    'Canceled': '抵消',
    'Annihilated an antimatter universe': '使反物质宇宙毁于湮灭。',
    'I said DON\'T let them touch.': '我是不是说过？ 别 让 它们相互接触！',
    'Evil Extinguisher': '涤荡邪秽',
    'Destroyed an evil universe': '摧毁邪恶宇宙。',
    'Never you will find a more wretched universe of scum and villainy.': '终于可以跟这个充满渣滓和败类的宇宙说再见了。',
    'I was god once': '我也做过神',
    'Destroyed a micro universe': '毁灭微型宇宙。',
    'You were doing very well, until everyone died.': '在每个人都死去之前你做的很不错。',
    'Power Word: Apocalypse': '真言术：启示录',
    'Destroyed a magic universe': '毁灭魔法宇宙。',
    'Some spells are forbidden for good reason.': '有些咒语之所以叫做禁咒是有原因的。',
    'Full Metal': '全金属',
    'Transmute an advanced resource': '转化出一种高级材料。',
    'You must destroy to create. That is the law of the universe.': '毁灭后再创造，这是宇宙的准则。',
    'You Shall Pass': '此路可通',
    'Collapsed the universe with unmodified Balorg': '在不修改炎魔特质的前提下，使宇宙毁于坍缩。',
    'You shall not pass! Unless you really want to.': '此路不通！除非……你一定要通过。',
    'Joyless': '无趣',
    'Colonized another world without joy': '无趣地定居到另一个星球上。',
    'There\'s no joy in this world': '这是一个没有欢笑的世界。',
    'What a Steel': '物美价廉',
    'Managed to Bioseed without ever figuring out how to make Steel': '在不知道如何冶炼钢的情况下进行播种重置。',
    'Seriously, what is it?': '说真的，那是什么？',
    'Dissipated': '消散',
    'Destroyed a decaying universe': '毁灭衰变的宇宙。',
    'It was dying anyway I guess.': '反正放着不管它也要完蛋了。',
    'Technophobe': '技术恐惧症',
    'Ascended with malfunctioning technology': '在电子技术经常暴走的条件下进行飞升重置。',
    'Energy hated you, now you are energy. Irony much?': '能量憎恨你，而你自己成为了能量，有趣吗？',
    'Wheelbarrow of Cash': '钱如废纸',
    'Acquired $250 billion dollars with inflation': '在通货膨胀的条件下获得 250000M 资金。',
    'It\'s all worthless.': '是不是该考虑金圆券了？',
    'Iron Will': '钢铁意志',
    'Survived the Cataclysm': '在大灾变中幸存下来。',
    'Nothing will stop you.': '没有什么能阻止你。',
    'Failed History': '失败的轮回',
    'Restarted the Cataclysm': '再次引发大灾变。',
    'Those who cannot remember the past are condemned to repeat it.': '吃一堑，而未长一智。',
    'Banana Smoothie': '香蕉奶昔',
    'Complete the Banana Republic objectives.': '完成香蕉共和国挑战。',
    'One export to rule them all.': '从单一出口到统治世界。',
    'Path Finder': '碳基黄昏',
    'Navigated the True Path to a resolution.': '在智械黎明剧情模式中找到一条出路。',
    'Just another fork in the road.': '啊，留下一条路等改日再见！但我知道路径延绵无尽头，恐怕我难以再回返。',
    'Ash and Dust': '尘归尘，土归土',
    'Launched the True Nuclear Apocalypse': '在智械黎明剧情模式中进行核爆重置。',
    'Welcome to the new age.': '欢迎来到新纪元。',
    'Exodus': '出埃及记',
    'Launched the Bioseed Ship inside the Truepath scenerio': '在智械黎明剧情模式中进行播种重置。',
    'It\'ll take much longer then 40 years.': '这次可能远不止 40 年了。',
    'Obsolete': '淘汰',
    'Triggerd an AI Apocalypse and got replaced by machines': '在智械黎明剧情模式中进行人工智能觉醒，使智械取而代之。',
    'This mission is too important for me to allow you to jeopardize it.': '这次任务对我来说很重要，我不允许你去破坏。',
    'Gross': '令人不适',
    'Achieved a greatness event while playing a stock race with the Ooze trait.': '使用拥有 [淤泥] 特质的非液体种族达到伟大。',
    'Icky': '黏糊糊的。',
    'Utopia': '乌托邦',
    //'Raised your morale to 500%': '将士气提升至 500%。', 在下方
    'Don\'t wake from the illusion.': '不要唤醒梦中人。',
    'Take no advice': '不听劝阻',
    'Ignored the warnings and played a non-demonic race on Hellscape until MAD': '在地狱星球上使用非恶魔种群进行核爆重置。',
    'Warnings are for sissies': '警告是给娘炮看的！纯爷们从不看警告！',
    'Ill Advised': '不理智',
    'Bioseeded from a Hellscape planet while playing a non-demonic race': '在地狱星球上使用非恶魔种群进行播种重置。',
    'Don\'t tell me what to do': '你在教我做事？',
    'Organ Harvester': '器官贩子',
    'Took the genetic rejects to space and spread their misery to another planet': '将基因灾难带上太空，并将他们的痛苦传向下一个星球。',
    'You created that new race just to steal their faces, didn\'t you?': '你只是为了他们的身体组织，才创造了他们，对吧？',
    'The Misery': '苦难',
    'Used the genetic rejects to initiate a late game reset option': '使用基因灾难，进行播种重置阶段之后的任意重置。',
    'You know you only had to MAD, right?': '你应该知道你只需要核爆重置的吧？',
    'Energizer': '劲量',
    'Ascended without building any thermal collectors.': '在不建造集热器的前提下，进行飞升重置。',
    'It just keeps going and going and going...': '永不疲倦，继续前进，前进，前进……',
    'Garbage Pie': '垃圾馅饼',
    'Ascended or Infused the genetic rejects without modifying them': '在不修改特质的前提下，使用基因灾难进行飞升重置或恶魔灌注。',
    'Hold nothing, extra onions.': '什么都不要，多放点洋葱。',
    'Crossed the Finish Line': '越过终点线',
    'Ascended or Infused during a Cataclysm': '在大灾变模式中进行飞升重置或恶魔灌注。',
    'Slow but steady wins the race.': '从容不迫，胜券在握。',
    'Blank Slate': '白板',
    'Removed all your major and genus racial traits': '移除所有种群特质和主修特质。',
    'A race is a race, but a blank slate could be anything; it could even be a boat!': '父亲在上，魂佑江东，公瑾在旁，智定天下！',
    'Supermassive': '超大质量',
    'Increase a black hole to 100 solar masses using mass ejectors': '使用质量喷射器将黑洞质量扩充到 100 个太阳质量。',
    'More like regular massive really': '真的，也没那么超大。',
    'Duke Steelem': '钢铁公爵',
    'Blew up a universe without ever understanding how to smelt steel': '在没有学会冶炼钢的情况下摧毁一个宇宙。',
    'Had balls of steel': '不作死就不会死。',
    'Banana Split': '香蕉船',
    'With the Banana Republic challenge active Export 500 of a resource and Import 500 worth of resources': '在香蕉共和国挑战中，出口500个物资并且进口500个物资。',
    'Peanut butter jelly time!': '香蕉你个芭乐！',
    'Rocky Road': '崎岖之路',
    'Bioseeded off of a planet with three poor geological traits': '在至少有 3 条矿产属性为匮乏的星球上进行播种重置。',
    'Ice cream not included': '不含冰淇淋。',
    'Demon Slayer': '斩妖除魔',
    'Killed 666 million demons': '杀死六亿六千六百万头恶魔。',
    'They are Legion': '他们是燃烧军团。',
    'Equilibrium': '平衡',
    'Attuned every species to the multiverse': '让所有种族都加入多元宇宙。',
    'Perfectly balanced, as all things should be.': '完美的平衡，万物本该如此。',
    'Digital Ascension': '机械飞升',
    'Ascended Unmodified Synth or Nano while playing with EM Field active': '使用合成人或纳米机器人，在不修改特质的前提下，在E.M.磁场模式中进行飞升重置。',
    'We have real souls afterall.': '我们不再只是冷冰冰的机器了。',
    'Trail Novice': '新手的足迹',
    'You have died of dysentery': '你死于痢疾。',
    'Gene Journeyman': '基因熟练工',
    'You have forded a river! You lost 2 oxen.': '你涉水过河，丢了两头牛。',
    'Adept': '专家',
    'You have exhausted the game in this area': '这一带的游戏你全玩完了。',
    'Master of Evolve': '进化大师',
    'Rafted down the Columbia river': '沿哥伦比亚河顺流而下。',
    'Grandmaster of Destiny': '命运宗师',
    'Congratulations! You have made it': '恭喜！你成功了！',
    'Nephilim': '奈非天',
    'Destroyed an Evil Universe using a Celestial race': '使用天堂种族摧毁邪恶宇宙。',
    'There is no cow level': '没有奶牛关。',
    'Twisted': '扭曲',
    'Fell to darkness as an Angelic creature': '成为堕入黑暗的天堂种族。',
    'All will be judged a sinner': '我们每个人都有罪。',
    'Slime Lord': '史莱姆王',
    'Elevated the lowliest creature into a great evil': '将最卑微的生物提升为大恶魔。',
    'I\'m not a bad Slime!': '我不是邪恶的史莱姆哟！',
    'Crystal Lake': '水晶湖',
    'A citizen drowned on Friday the 13th.': '有人在黑色星期五溺毙了。',
    'You should abandon that lake...': '真不该靠近那个湖的……',
    'Love of Idle': '放置情人节',
    'Loved idling with your civilization on Valentine\'s Day': '在情人节充满爱地放置你的文明。',
    'They didn\'t even send flowers': '连花都没送！',
    'Unlucky': '不幸',
    'Idled while a leprechaun stole your gold': '放置时一个小妖精偷走了你的黄金。',
    'It\'s a good thing gold is not a resource': '幸好黄金不是资源。',
    'Hopper': '跳跳兔',
    'Idled around while a bunny hopped all around you.': '一只兔子绕着无所事事的你蹦蹦跳跳。',
    'Did you find all the candy?': '找到所有糖果了吗？',
    'Egg Hunt': '猎蛋行动',
    'Found at least 12 hidden eggs during the Easter event.': '在复活节活动期间至少找到 12 个隐藏彩蛋。',
    'I hope you found them before they started to smell': '希望你在蛋发臭前找到它们。',
    'Launch Day': '游戏发布纪念日',
    'Idled a civilization during Launch Day': '在游戏发布纪念日期间放置你的文明。',
    'To infinity and beyond!': '飞向宇宙，浩瀚无垠！',
    'Solstice Festival': '夏至篝火狂欢',
    'Burn 1 Million Thermite during the solstice Festival.': '在夏至篝火狂欢活动期间燃烧一百万单位铝热剂。',
    'Burn it to the ground.': '为什么我的手中多了火把和汽油？',
    'Firework Festival': '烟花狂欢',
    'Activate the Firework Factory during the Firework Festival.': '在烟花狂欢活动期间开启烟花厂。',
    'Boom!': '轰！',
    'Boo!': '血溅万圣劫',
    'Idled a civilization during Halloween': '在万圣节期间放置你的文明。',
    'Who you gonna call?': '该找谁帮忙？',
    'Trick or Treat!': '不给糖就捣蛋！',
    'Found at least 12 Candies and Ghosts during the Trick or Treat event.': '在万圣节活动期间至少找到合计 12 个糖果和幽灵。',
    'Candy Corn Sucks': '玉米糖太难吃了！',
    'Gobble Gobble': '狼吞虎咽',
    'Idled a civilization during Thanksgiving week': '在感恩节期间放置你的文明。',
    'Time for a food coma': '差不多该餐后困倦了……',
    'Ho! Ho! Ho!': '吼！吼！吼！',
    'Idled a civilization during Christmas': '在圣诞节期间放置你的文明。',
    'Help! I\'m stuck in a chimney!': '救命！我被卡在烟囱里了！',
    'The Fool': '愚蠢的土拨鼠！',
    'Freaked out about your achievements': '你的成就令人折服！',
    'April Fools!': '愚人节快乐！',
    'Purify': '净化',
    'Each Spire level completed slightly purifies the miasma around the island making Purifier, Harbour, Port, and Base Camp creep cheaper.': '每通过一层尖塔，可以略微净化尖塔之岛周围的毒气，从而使空气净化器、血湖港口、登陆点、登陆营地的成本蠕变降低。',
    'Chum the Waters': '湖水亲和',
    'Increases the effectiveness of Bireme Warships by +5%.': '双层排桨军舰的效率 +5%。',
    'Blood Lust': '嗜血',
    'Increases the training bonus from boot camps by +0.2%.': '新兵训练营的效率 +0.2%。',
    'At Level': '等级',
    'Illuminate': '照明',
    'Increases the output of Swarm Satellites by +0.01.': '蜂群卫星的发电量 +0.01MW。',
    'Greed': '贪婪',
    'Increases the money storage of banks by +1%.': '银行资金上限 +1%。',
    'Hoarder': '囤积者',
    'Increases warehouse storage by +1%.': '仓库储量上限 +1%。',
    'Artisan': '工匠',
    'Increases Craftsmen output by +1%.': '工匠产量 +1%。',
    'Soul Trap': '灵魂陷阱',
    'Increases the number of souls trapped by Soul Attractors by +5.': '灵魂引渡器吸引灵魂数量 +5。',
    'Wrath': '愤怒',
    //'Increases Spire Mech power by 5%': '尖塔机甲的效率 +5%。', 在下方
    'Prepared': '整备',
    'Add an extra equipment slot to all mechs.': '所有机甲额外增加 1 个装备位。',
    'Compact Machines': '机甲小型化',
    'Standard, Heavy, and Titan class mechs require less bay space. Scout Mechs are cheaper to build.': '标准、重型、泰坦机甲的机舱空间需求降低，侦察型机甲的建造成本降低。',
    'Infernal Machines': '机甲地狱化',
    'You can optionally construct more expensive versions of your mechs.': '你可以选择建造更昂贵更强力的机甲。',
    'Unbound': '自由',
    'Can play Aquatic, Fey, Heat, Polar, and Sand races on the wrong biome planets with a penalty.': '你可以在任意星球上进化出海洋、精怪、烈焰、极地和沙漠生物了，但如果环境不匹配，则全局产量会受到一定惩罚。',
    'Unbound Resistance': '自由抗体',
    'Reduces the wrong genus type penalty to 10%.': '在“错误”星球上进化出的生物，全局产量惩罚降低到 10%。',
    'Shadow War': '暗影战争',
    'Can play Demonic and Angelic races on the wrong biome planets with a penalty.': '你可以在任意星球上进化出天堂和恶魔生物了，但如果环境不匹配，则全局产量会受到一定惩罚。',
    'Unbound Immunity': '自由免疫',
    'Reduces the wrong genus type penalty to 5%.': '在“错误”星球上进化出的生物，全局产量惩罚降低到 5%。',
    'Blood Awareness': '鲜血认知',
    'Blood Infusion tab unlocks with A.R.P.A.': '解锁 A.R.P.A. 面板时同时解锁 鲜血灌注 面板。',
    'Custom Race': '自建种族',
    'Your custom race.': '您的自建种族。',
    'Human': '人类',
    'Humans are versatile creatures who are adept at bending the environment around them to suit their needs. They are an ambitious race who seek to expand their knowledge of the universe around them and build great empires.': '人类相当多才多艺，他们善于改变周边环境以适应自己的需要。他们野心勃勃，想要扩展自己对宇宙的认知，最终建立伟大的帝国。',
    'Elf': '精灵',
    'Elves are typically tall and slender creatures with pointy ears, they tend to be reclusive but sharp of wit. Elves live long lives and often devote themselves to study, seeking answers to the deep fundamental questions of the universe.': '精灵通常十分高大而瘦削，长有尖耳。他们虽然机智敏锐，但往往避世绝俗。他们非常长寿，常常把时间花在研究探寻宇宙本源的解答上。',
    'Orc': '兽人',
    'Orcs tend to be large and muscular creatures who are slow of wit but contain immense brute strength. They typically try to solve problems with violence first, then seek a more rational solution only when that doesn\'t work.': '兽人往往体型庞大，肌肉发达，头脑迟钝。他们喜欢用暴力解决问题，行不通的时候才会考虑理性沟通。',
    'Cath': '猫族',
    'The cath are a feline race who are typically lazy. They are curious and love exploring the unknown. However, most Cath prefer to laze about rather than work hard.': '猫族通常相当懒散。他们充满好奇，喜欢探索未知，但大部分时候他们宁可偷懒。',
    'Wolven': '狼人',
    'The Wolven are a canine race who usually move in organized packs. They are a highly social species and rarely undertake any task alone.': '狼人喜欢成群结队活动。他们高度社会化，几乎不独自承担任务。',
    'Vulpine': '妖狐',
    'The %0 are a playful species of %1 fox. They are cunning and have a bushy tail.': '妖狐是一种贪玩的红色狐狸。他们相当狡黠，长有毛茸茸的尾巴。',
    'Centaur': '半人马',
    'Centaur are a species of horse creatures who have human-like upper bodies. They are fast moving and strong.': '半人马的上半身与人相似，但下半身却是马。他们行动迅捷，身体强壮。',
    'Rhinotaur': '犀牛',
    'Rhinotaur are tough beastial creatures who have a large horn attached to their nose.': '犀牛相当强壮，鼻子上长有大角。',
    'Capybara': '水豚',
    'The Capybara are highly evolved giant rodents. They have sharp teeth that grow constantly and require grinding.': '水豚是高度进化的巨型啮齿动物，他们锋利的牙齿会不断生长，需要经常磨牙。',
    'Kobold': '狗头人',
    'Kobolds are small humanoid creatures who are known for their infatuation with candles. They are adept at hoarding as much stuff as possible.': '狗头人身型矮小，以迷恋蜡烛而闻名。他们善于尽可能地囤积东西。',
    'Goblin': '哥布林',
    'Goblins are small humanoid creatures who are known for their greed and cunning. They are highly intelligent but typically selfish in nature.': '哥布林身型矮小，以贪婪和狡猾而闻名。他们非常聪明，但天性自私。',
    'Gnome': '侏儒',
    'Gnomes are small humanoid creatures who are known for their superior intelligence. They are natural scientists and seek to expand their knowledge, often at the cost of safety and morality.': '侏儒身型矮小，以高智商而闻名。他们是天生的科学家，常常不顾安全和道德问题而追寻知识。',
    'Ogre': '食人魔',
    'Ogres are large humanoid creatures who are known for being kind of dumb. They are very strong with few races being able to match their physical prowess. However, they learn slowly.': '食人魔身型巨大，以愚蠢而为人熟知。他们强壮到无可匹敌，但学得很慢。',
    'Cyclops': '独眼巨人',
    'Cyclops are large humanoid creatures who have a single giant eye. They have poor depth perception but are fairly social and intelligent.': '独眼巨人身型巨大，只有一只巨眼。他们的距离感很糟糕，但社会化程度很不错，也很聪明。',
    'Troll': '巨魔',
    'Trolls are large humanoid creatures who are known for their regenerative powers. They are a hardy race highly resistant to disease and injury.': '巨魔身型巨大，以超强的恢复能力而闻名。他们对疾病和受伤有着很强的抵抗力。',
    'Tortoisan': '乌龟人',
    'Tortoisans are a reptilian species with %0 shells on their backs. They are slow moving and good at hiding.': '乌龟人背上长有绿色壳，行动缓慢，善于躲藏。',
    'Gecko': '壁虎人',
    'The Geckos are a lizard species who can naturally camouflage themselves to their surroundings. They are very agile and fast moving.': '壁虎人可以自然地将自己融入周围环境以进行伪装。他们非常敏捷，行动迅速。',
    'Slitheryn': '娜迦',
    'Slitheryn are a reptilian species who evolved from snakes. They have humanoid upper bodies but retain snake-like lower halves.': '娜迦由蛇进化而来。他们拥有人类的上半身和蛇形的下半身。',
    'Arraak': '陆行鸟',
    'Arraak are a feathered species of flightless birds. Long ago they may have taken to the skies but modern Arraak are too heavy to fly.': '陆行鸟浑身长满羽毛，却不会飞行。或许他们的先祖曾经可以飞上天空，但现在他们已经重到飞不了了。',
    'Pterodacti': '翼手龙',
    'Pterodacti are descended from large featherless flying creatures. Their skin is leathery and they have long, narrow heads.': '翼手龙的祖先是一种大型无羽毛的飞行生物。他们皮肤坚韧，头又长又窄。',
    'Dracnid': '天龙',
    'Dracnid are descended from large scaly flying creatures. They are tough due to their natural armor, but they tend to be anti-social and greedy.': '天龙的祖先是一种大型有鳞飞行生物。由于身披鳞甲，他们并不容易受伤，但他们社会化程度不高，而且十分贪婪。',
    'Ent': '树人',
    'Ents are basically sentient trees who can uproot themselves and move around. They are large and slow moving, but fearsome and can get most of their nutrients from the sun.': '树人可以将自己从地里拔起并正常行动。他们体型庞大，行动缓慢，令人生畏。他们可以从阳光里获取大部分营养。',
    'Cacti': '仙人掌',
    'Cacti are small sentient plant creatures covered in spines. They are surprisingly fast moving, but easily startled.': '仙人掌浑身布满了刺。他们的移动速度惊人，但易受惊吓。',
    'Pinguicula': '捕虫堇',
    'The Pinguicula are a plant based species who are covered in a sticky film used to trap small prey. They are well suited to nutrient poor environments.': '捕虫堇覆盖有粘性薄膜，用来捕捉小型猎物，可以在残酷的环境下生存。',
    'Sporgar': '孢子虫',
    'Sporgar are a parasitic species of sentient mold spores that spread by infecting host bodies and possessing them.': '孢子虫是有知觉的寄生真菌孢子，通过感染并控制宿主的身体来传播。',
    'Shroomi': '蘑菇人',
    'The Shroomi are a race of mushroom-like creatures. They prefer dark places away from sunlight.': '蘑菇人长相与蘑菇相似，性情喜阴。',
    'Moldling': '霉菌人',
    'The Moldling are a race of blob like creatures made of a mass of mold which can shape itself into any form they please.': '霉菌人由大量霉菌构成，可以变换成任何形状。',
    'Mantis': '螳螂人',
    'Mantis are an insectoid species that resemble giant... mantis. They are quick but fragile.': '螳螂人长得很像巨型螳螂，他们行动迅捷，但很脆弱。',
    'Scorpid': '蝎子人',
    'Scorpid are a bipedal species with large claw hands and barbed tails. They are tough fighters naturally equipped for close combat.': '蝎子人是直立行走的两足动物，拥有巨大的爪子和带刺的尾巴。他们天生就拥有强大的近战能力。',
    'Antid': '蚂蚁人',
    'Antid are a hivemind species descended from ants. Individually they are not intelligent but as their swarm increases so does their collective intelligence.': '蚂蚁人由蚂蚁进化而来，拥有蜂群思维。他们的个体并不聪明，但随着族群壮大，他们的智慧也会不断增长。',
    'Sharkin': '鲨鱼人',
    'Sharkin are an aquatic species descended from aggressive fish that have large mouths with many sharp teeth. Although they can roam on land they prefer to stay underwater.': '鲨鱼人由一种长有血盆大口和尖牙利齿的攻击性鱼类进化而来。他们可以在陆地上行动，但更愿意呆在水下。',
    'Octigoran': '八爪鱼',
    'Octigoran are an aquatic species of cephalopod who have eight tentacles. They can mimic walking on land using their appendages as makeshift legs, but are most at home underwater.': '八爪鱼是水生头足类动物，有八只触手。他们可以使用触手在陆地上行走，但大部分时候还是呆在水下。',
    'Dryad': '树妖',
    'Dryads are forest creatures that are deeply connected to their trees. They can be quite ruthless if anyone threatens their trees.': '树妖与树木的联系极为紧密，如果有人威胁到了他们的树木，他们会变得非常残酷无情。',
    'Satyr': '萨提尔',
    'Satyrs are whimsical goat men that prefer to party rather than work. They are like a society of frat boys.': '萨提尔是满脑子奇思妙想的山羊人，喜欢聚会，不喜欢工作。社会结构类似于海军马鹿。',
    'Phoenix': '不死鸟',
    'Phoenixes are avians that constantly emanate heat. When they die, they can sometimes self-resurrect in an explosion of fire.': '不死鸟周身都散发着高温热量。当死去时，他们可能在一阵火焰爆炸后涅槃重生。',
    'Salamander': '火蜥蜴',
    'Salamanders are descended from lizards who evolved around lava flows. They can exhale intense flames and are not to be trifled with.': '火蜥蜴由熔岩流周围的蜥蜴进化而来。他们可以喷出猛烈的火焰，轻视他们的人会大吃苦头。',
    'Yeti': '雪怪',
    'Yeti are polar apes which dislike hot locations. For some reason pictures of them are always blurry.': '雪怪是不喜欢炎热的极地猿。他们的照片总是模糊不清，谁也不明白背后的原因是什么。',
    'Wendigo': '温迪戈',
    'Wendigos are horrific creatures that were born in the coldest climates. They have ravenous appetites which are never sated, and they feed only on the souls of other creatures.': '温迪戈是在最严寒气候下孕育的恐怖生物。他们有着如饕餮般无休止的胃口，且只以其他生物的灵魂为食。',
    'Tuskin': '塔斯肯',
    'Tuskin evolved in the deserts and are normally hostile to anyone who is not part of their clan. They will often attack strangers for any resources they might provide.': '塔斯肯生于沙漠，对外族通常怀有敌意。他们经常攻击陌生人以获取资源。',
    'Kamel': '骆驼人',
    'The Kamel are a race of humanoids with a giant hump on their back. They can go for long periods of time without drinking water.': '骆驼人是一种背上长有驼峰的人型生物。他们长时间不喝水也可以维持生命。',
    'Balorg': '炎魔',
    'Balorg are a fiery race of demons who inhabit the abyss. Their skin literally burns with hellfire and few who gaze upon them live to tell the tale.': '炎魔居住在无底深渊，他们的皮肤上燃烧着地狱之火，见过他们的人几乎没有能活着回来的。',
    'Imp': '小恶魔',
    'Imps are a small race of demonic creatures who delight in tormenting their victims with pranks that are far from harmless.': '小恶魔身型矮小，喜欢通过各种伤害很大的方式折磨受害者。',
    'Seraph': '大天使',
    'Seraph are a race of angelic beings who inhabit the mountains of Eden. Although they champion the light, they won\'t hesitate to smite evil wherever it is found.': '大天使居住于伊甸山之上。他们为光明而战，哪里有邪恶，哪里就有他们挺身作战的身影。',
    'Unicorn': '独角兽',
    'Unicorns are mythical creatures of the light who roam the plains of Eden. Despite their reputation for good, unicorns are quite vicious when challenged.': '独角兽在伊甸平原上随意游荡，他们是神话中的光之生物。尽管声誉良好，但独角兽在遭遇挑战时会变得极度狂暴。',
    'Synth': '合成人',
    'Synths are androids that have been covered in organic flesh to look just like their creator race. To an outside observer they appear indistinguishable from fully organic %0.': '合成人的内部由机械构成，但外表覆着一层有机体的身体组织，外观上与他们的造物主几乎一致。',
    'Nano': '纳米机器人',
    'The Nano are swarms of tiny robots that work together to form larger entities. Each nano citizen is made up of trillions of individual nanites.': '纳米机器人由极小型的机器人集群组装构成。每个纳米机器人都由数万亿纳米体组成。',
    'Valdi': '瓦尔迪',
    'The Valdi are a genetic disaster, it\'s a wonder they have survived this long.': '瓦尔迪简直就是基因灾难，他们能够生存下来已经是奇迹。',
    'Sludge': '软泥',
    'The Sludge are a pathetic genetic disaster of ooze made self aware, it\'s a wonder they can function at all.': '软泥是一种可悲的基因灾难，他们能够觉醒意识并正常行动就已经是奇迹了。',
    'Genetic Memory': '遗传记忆',
    'Reduces cost creep by': '成本蠕变 -',
    'Animus': '阿尼姆斯',
    'Divine Remembrance': '神圣的回忆',
    'Divine Proportion': '黄金分割比',
    'Genetic Repository': '基因库',
    'Spatial Reasoning': '空间推理',
    'Plasmids boost storage space': '质粒可以增加储量上限',
    'Spatial Superiority': '空间优势',
    'Plasmid storage effect +': '质粒储量上限效果 +',
    'Spatial Supremacy': '空间霸权',
    'Dimensional Warping': '维度扭曲',
    'Both Phage and Plasmids apply the Spatial Reasoning bonus': '噬菌体也可以增加储量上限',
    'Enhanced Muscle Fiber': '肌肉纤维强化',
    'Doubles manual gathering rate': '手动收集效率翻倍',
    'Morphogenesis': '形态发生',
    'Decreases evolution costs': '降低进化成本',
    'Recombination': '重组',
    'Gain a minor trait when evolving': '进化完成后，随机选取一个次要特质，升 1 级。',
    'Homologous Recombination': '同源重组',
    'Gain 2 ranks of a second minor trait when evolving': '进化完成后，随机选取一个次要特质，升 2 级。',
    'Genetic Reshuffling': '遗传改组',
    'Gain 3 ranks of a third minor trait when evolving': '进化完成后，随机选取一个次要特质，升 3 级。',
    'Recombinant DNA': '重组DNA',
    'Gain 4 ranks of a fourth minor trait when evolving': '进化完成后，随机选取一个次要特质，升 4 级。',
    'Chimeric DNA': '嵌合DNA',
    'Gain 5 ranks of a fifth minor trait when evolving': '进化完成后，随机选取一个次要特质，升 5 级。',
    'Molecular Cloning': '分子克隆',
    'Gain 6 ranks of a sixth minor trait when evolving': '进化完成后，随机选取一个次要特质，升 6 级。',
    'Transgenes': '转殖基因',
    'Gain 7 ranks of a seventh minor trait when evolving': '进化完成后，随机选取一个次要特质，升 7 级。',
    'Synthesis': '合成',
    'Karyokinesis': '核分裂',
    'Cytokinesis': '胞质分裂',
    'Mitosis': '有丝分裂',
    'Metaphase': '分裂中期',
    'Mutation': '突变',
    'Gain the ability to spend Plasmids remove major racial traits': '你可以使用质粒移除主修特质了。',
    'Transformation': '转换',
    'Gain the ability to spend Plasmids to remove genus racial traits': '你可以使用质粒移除种群特质和主修特质了。',
    'Metamorphosis': '变形',
    'Gain the ability to spend Plasmids to gain major racial traits from other species of the same genus': '你可以使用质粒获得同种群其他种族的主修特质了。',
    'Replication': '复制',
    'Increases Birth Rate': '提高出生率',
    'Artificer': '技工',
    'Doubles the rate at which craftsmen work.': '工匠产量 +100%（原料消耗同样翻倍）',
    'Detail Oriented': '注重细节',
    'Rigorous': '一丝不苟',
    'Geographer': '地理学家',
    'Start new games with the build and research queue unlocked': '开局解锁建筑队列和科研队列',
    'Architect': '建筑师',
    'Double the maximum number of construction and research projects that can be queued': '建筑队列和科研队列的上限翻倍',
    'Governance': '总督',
    'Unlock the ability to assign governors to automate some basic tasks.': '解锁总督，可以自动进行一些基础操作',
    'Hardened Genes': '基因硬化',
    'Unlocks challenge traits': '解锁挑战基因',
    'Unlocked': '基因解锁',
    'Achievements grant a small production bonus': '成就可以提供精通加成',
    'Universal': '宇宙共同体',
    'Universe specific mastery is increased in value': '宇宙专属精通的数值增加',
    'Standard': '宇宙准则',
    '80% of standard mastery works in alternate universes': '宇宙专属精通数值 -20%，通用精通数值 +20%。',
    'Mastered': '精通掌控',
    'Unlocks the mastery gene': '解锁 [精通] 次要特质',
    'Negotiator': '谈判专家',
    'Mastery increases volume of goods gained from trade routes': '利用贸易路线购买的货物数量可以受精通加成',
    'Ancients': '先祖',
    'Unlocks second tier religion upgrades': '解锁二级宗教升级',
    'Faith': '信仰',
    'Unlocks the priest job': '解锁牧师职业',
    'Devotion': '敬拜',
    'Priests are more effective': '提升牧师效率',
    'Acolyte': '助手',
    'Ziggurats increase the priest cap': '通灵塔可以提升牧师上限',
    'Conviction': '信念',
    'Priests are even more effective': '进一步提升牧师效率',
    'Transcendence': '超越',
    'You can unlock both Fanaticism and Anthropology': '你可以同时研究狂热信仰和人类学',
    'Bleeding Effect': '出血效应',
    'Synchronicity': '同步原则',
    'Astral Awareness': '星体认知',
    '20% of Plasmids boost storage in antimatter universe, and 10% of Anti-Plasmids boost storage outside of antimatter universe': '在反物质宇宙中，可以有总数 20% 的质粒对储量上限生效，在反物质宇宙以外的宇宙中，可以有总数 10% 的反质粒对储量上限生效',
    'Blood Remembrance': '鲜血记忆',
    'Keep your Blood Stones after a reset': '威望重置后鲜血之石数量不变',
    'Blood Sacrifice': '血祭',
    'Earn double the Blood Stones from clearing Spire levels': '通过一层尖塔后获得双倍鲜血之石',
    'Essence Absorber': '精华吸收',
    'Unlock advanced Blood Infusions': '解锁鲜血灌注的高阶升级',
    'Most storage is increased by 5% / 10% / 15% / 20% /': '大多数物资的储量上限 +5% / 10% / 15% / 20% /',
    'Trade import volume is increased by 2% / 4% / 6% / 8% / 10% and trade export volume is decreased by 1% / 2% / 3% / 4% / 5%.': '进口货物数量 +2% / 4% / 6% / 8% / 10%，出口货物数量 -1% / 2% / 3% / 4% / 5%。',
    'Gain 1.5x / 2x / 2.5x / 3x / 3.5x more Genes from mutations': '通过基因突变获得的基因数量变为原来的 1.5 / 2 / 2.5 / 3 / 3.5 倍',
    'You can evolve into a race of your choice on MAD resets': '进化阶段，可以选择进化为已经核爆重置过的种族',
    'Start with 0% / 50% / 100% / 150% / 200 bonus RNA and DNA during evolution': '进化阶段，开局获得 0% / 50% / 100% / 150% / 200% RNA 和 DNA',
    'Gain +1 / +2 / +3 / +4 / +5 free extra planet options during bioseeding': '播种重置后，可选星球数量 +1 / 2 / 3 / 4 / 5',
    'See the numerical values of 1 / 2 / 3 / 5 / 7 of a planet\'s geology deposits during planet selection': '选择星球时，可以看到星球矿产属性的具体数值，但至多只能看到 1 / 2 / 3 / 5 / 7 项数值',
    'Gain +1 base knowledge generation and +900 base knowledge storage': '知识基础产量 +1，知识基础上限 +900',
    'Max Morale is increased by +2% / +4% / +6% / +8% / +': '士气上限 +2% / 4% / 6% / 8% / ',
    'Steel smelting is boosted by 2% / 4% / 6% / 8% /': '钢产量 +2% / 4% / 6% / 8% /',
    '2% / 4% / 6% / 8% / 10% Bank Vault Storage': '2% / 4% / 6% / 8% / 10% 银行保险库资金上限',
    '3% / 6% / 9% / 12% / 15% Dark Energy Effect in %1 universe': '3% / 6% / 9% / 12% / 15% 当前宇宙中的暗能量效果',
    'Can roll Iridium deposits on the moon during planet selection': '星球矿产属性中可以出现铱了',
    'Max quality of geology deposits increased by 5% / 10% / 15% / 20% /': '星球矿产属性范围上限 +5% / 10% / 15% / 20% /',
    'Number of geology rolls increased by 1 / 2 / 3 / 4 /': '星球矿产属性条数上限 +1 / 2 / 3 / 4 /',
    'Transport fuel costs reduced by 4% / 8% / 12% / 16% /': '燃料成本 -4% / 8% / 12% / 16% /',
    'Coal Powerplants generate +1MW energy': '煤电厂发电量 +1MW',
    'Oil Powerplants generate +1kW (2-star) / +2 (4-star)MW energy': '石油发电厂发电量 +1MW(铜星) / 2MW(金星)',
    'Casinos require 1MW less energy': '赌场电力消耗 -1MW',
    'Mass drivers require 1MW less energy': '质量驱动器电力消耗 -1MW',
    '50% Railway Trade Profitability': '50% 铁路贸易盈利',
    '1 Railway Trade Route': '1 铁路贸易路线',
    '10% Crate Storage': '10% 板条箱储量',
    'Tourist Center generates $3 per Trade Post': '每建造一个贸易站，就使游客中心收入 +$3',
    'Freight Yard & Container Port creep -': '货场与集装箱港口的成本蠕变 -',
    'Reduce time before government can be changed again by -10% / -20% / -30% / -40% / -50% after a revolution.': '改革政府体制的冷却时间 -10% / 20% / 30% / 40% / 50%。',
    '1 gene during custom species creation per star level per universe (max of +5 genes per universe). This perk is not currently listed on the stats page in-game.': '1 自定义种族时的基因点数(每个宇宙最多 +5 点)。',
    '0 Star: Start with 25 Steel.': '无星：开局拥有 25 钢。',
    '1 Star: Thermal Collector +10% Efficiency': '白星：集热器效果 +10%。',
    '2 Star: Start with bonus Soul Gems. (1 per universe completion': '铜星：开局拥有额外的灵魂宝石。(每在一个宇宙中完成金星的本成就，就增加 1 ',
    '3 Star: Additional Thermal Collector +15% Efficiency': '银星：集热器效果再 +15%。',
    '4 Star: +10% Soul Gem drop rate.': '金星：灵魂宝石掉率 +10%。',
    '4 Star: +5% Thermal Collector Efficiency per 3-star achievement in non-standard universes': '金星：每在非标准宇宙中完成金星的本成就，集热器效果就再增加 5%',
    '1 / +2 / +3 / +4 / +5 custom race complexity per star level': '+1 / +2 / +3 / +4 / +5 基因奢侈税基础值。自定义种族选择的正面特质数量超出基础值时，将触发基因奢侈税，原基础值为 2 个，现额外增加相应数量。',
    'Solar Swarm Satellites +0.15 Power.': '蜂群卫星基础发电量 +0.15MW。',
    '10% Factory Production.': '10% 工厂产量。',
    '6% Mining Drone Output.': '6% 采矿无人机产量。',
    '1 Spaceport Support.': '1 太空港支持。',
    'Unlocked Space Casinos for normal game use.': '在大灾变剧情模式以外，也可以使用太空赌场。',
    '1 Geothermal Energy.': '2 地热发电厂基础发电量',
    '20% / 40% / 60% / 80% / 100% Spire Mech Attack Power.': '20% / 40% / 60% / 80% / 100% 尖塔机甲攻击力。',
    '0 Star: Base Freight Yard Crates +10.': '无星：货场的板条箱基础上限 +10。',
    '1 Star: Base Container Port Containers +10.': '白星：集装箱港口的集装箱基础上限 +10。',
    '2 Star: Iridium Smelting Available outside Truepath.': '铜星：在智械黎明剧情模式以外，冶炼厂也可以冶炼铱。',
    '3 Star: Not available in current game version': '银星：当前版本不可用',
    '4 Star: Not available in current game version': '金星：当前版本不可用',
    'Base RNA generation +0.5x / +1x / +1.5x / +2x / +2.5, Base DNA generation +0.25x / +0.5x / +0.75x / +1x / +1.25.': 'RNA 基础产量 +0.5 / 1 / 1.5 / 2 / 2.5，DNA 基础产量 +0.25 / 0.5 / 0.75 / 1 / 1.25。',
    'Extra minor trait info revealed in Genetics Lab.': '你可以在 基因 子面板下查看次要特质的详细信息。',
    '1 / +1 / +2 / +2 / +3 Research Queue, +0 / +1 / +1 / +2 / +2 Build Queue.': '1 / +1 / +2 / +2 / +3 科研队列上限，+0 / +1 / +1 / +2 / +2 建筑队列上限。',
    'Extra main trait info revealed in Genetics Lab.': '你可以在 基因 子面板下查看种群特质和主修特质的详细信息。',
    'Start with +100 / +200 / +300 / +400 / +500 Lumber, Stone, and Food. Base Lumber and Stone cap increased by +60 / +120 / +180 / +240 / +300.': '开局获得 100 / 200 / 300 / 400 / 500 木材，石头和食物。木材和石头的基础储量上限 +60 / +120 / +180 / +240 / +300。',
    'Achievement Not Awarded': '成就未获得',
    'Upgrade Purchased': '升级已购买',
    'Upgrade Purchased (Level': '升级已购买(等级',
    'Overall': '总体',
    'Standard Universe': '标准宇宙',
    'Heavy Universe': '高引力宇宙',
    'Micro Universe': '微型宇宙',
    'Evil Universe': '邪恶宇宙',
    'Antimatter Universe': '反物质宇宙',
    'Magic Universe': '魔法宇宙',
    'Gene Lab Calculator': '基因实验室计算器',
    'Load save data to view the calculator.': '导入存档后方可使用基因实验室计算器。',
    'Genes Remaining': '剩余基因点数',
    'Species Name': '种族名称',
    'Species Short Desc': '简单描述',
    'Species Long Desc': '具体描述',
    'Homeworld': '家园星球',
    'Red Planet': '红色星球',
    'Hell Planet': '地狱星球',
    'Gas Giant': '气体巨星',
    'Gas Giant Moon': '气体巨星卫星',
    'Dwarf Planet': '矮行星',
    'Traits': '特质',
    'Humanoid': '人',
    'Carnivorous Beast': '肉',
    'Herbivorous Beast': '草',
    'Small': '矮',
    'Giant': '巨',
    'Reptilian': '爬',
    'Avian': '翼',
    'Insectoid': '虫',
    'Plant': '植',
    'Fungi': '菌',
    'Aquatic': '海',
    'Fey': '怪',
    'Heat': '焰',
    'Polar': '寒',
    'Sand': '沙',
    'Demonic': '魔',
    'Angelic': '天',
    'Synthetic': '机',
    'Your race is more easily modified by gene therapy. Your race is wasteful and uses extra materials to craft things.': '基因组测序时间 -10%。锻造物的原料消耗 +10%。',
    'Your species is carnivorous and does not engage in agriculture. Your bestial instincts improves your hunting skills and makes training soldiers easier. Your race is less effective at combat when it is precipitating.': '猎人取代失业人口出现。无法研究农业。每秒浪费 50% 的食物，此数值可由建造烟房而降低。狩猎产量 +8%，有风时，狩猎产量变为 +15%。士兵训练速度 +10%。下雨时战斗评级 -10%。',
    'Your species does not eat meat. Your highly toned instincts help you avoid danger.': '狩猎无法获得食物。50% 死亡士兵变为伤兵，勘探者死亡率 -10%，仙女座星云任务的舰船损失减半，且舰船可以更好地降低海盗威胁度。',
    'Your race is small and thus requires less materials to build things. Your race is ineffective at tough manual labor.': '地面建筑成本蠕变 -0.01，太空建筑成本蠕变 -0.005。伐木工人，石工、回收者、水晶矿工、矿工和煤矿工人的产量 -10%。',
    'Your race is large and thus requires extra materials to build things. Your race has great strength and can harvest the basics in greater quantity.': '地面建筑成本蠕变 +0.005。手动收集资源获取量变为正常的 5 倍。（食物、木材、石头）',
    'Your species is sensitive to the outside temperature. Your species is protected by scales which act as a kind of natural armor.': '农民、伐木工人、石工、回收者、水晶矿工、矿工和煤矿工人：寒冷或下雨时产量 -20%，炎热或晴天时产量 +10%。战斗胜利时，士兵战死数量 -2, 战斗失败时，士兵战死数量 -1，地狱维度巡逻队护甲 +1。',
    'Your species has light-weight bones and requires less crafted materials to build structures. Your race has a stiff skeletal structure and crafts less efficiently.': '锻造物消耗 -5%。锻造物产量 -1%。',
    'Your species gestates quickly, population thus raises faster than other species. Your species metabolizes food quickly, as a result you need more of it.': '人口增长速率增加。特质级别影响人口增长速率。食物消耗 +5%。',
    'Your people naturally produce sap which can be hardened into a useful building material called Amber. Your species is asymmetrical. This gives you a more monstrous appearance, making trade more difficult.': '琥珀取代石头出现。市民和士兵的琥珀基础产量为每秒 0.6。市场出售价格 -20%，如果同时拥有 [商人] 特质，则此特质不生效。',
    'You consume dead matter for nutrition. Your species doesn\'t propagate when it\'s precipitating.': '堆肥科技取代农业科技。基础食物产量因子为 80。下雨时人口停止增长（该特质优先级高于 [寄生虫] 特质和 [孢子] 特质）。',
    'Your species lives primarily underwater and is thus not affected by most weather. Sunlight does not penetrate into the depths of the ocean easily and farming activities are less effective as a result.': '士气不受天气影响。农场及农民产量 -10%。',
    'Your spies rarely, if ever, get caught. Iron is toxic to you, it must be handled with care thus making mining and refining it slower.': '间谍永远不会被抓捕，地狱维度巡逻队被攻击的概率 -67%，无法与 [变色龙] 特质叠加。铁产量 -25%。',
    'You revel in hot weather, gaining increasing production the longer it lasts. You despise cold weather, losing increasing production the longer it lasts.': '春天无士气加成，夏天士气 +5%。连续炎热天气会叠加全局产量加成效果，前100天每天 +0.35%，100天以后每天 +0.2%。木材资源被去除，额外增加温石棉资源，由石工采集。大部分资源成本 -10%。连续寒冷天气会叠加产量惩罚效果，每天 -0.25%。',
    'You revel in cold weather, gaining increasing production the longer it lasts. You despise hot weather, losing increasing production the longer it lasts.': '春天无士气加成，冬天士气 +5%。连续寒冷天气会叠加全局产量加成效果，前100天每天 +0.35%，100天以后每天 +0.2%。寒冷时食物产量 +20%，下雪时食物产量 +10%，晴天时食物产量 -15%。连续炎热天气会叠加产量惩罚效果，每天 -0.25%。',
    'You can assign scavengers to look for useful items which boost productivity. Your nomadic lifestyle makes established trade more difficult.': '总是可以从事拾荒者工作（每位拾荒者使全局产量 +0.12%）。垃圾星球上拾荒者效率 +25%。贸易站的贸易路线 -1',
    'Your race is immoral and delights in conflict. Your race is pure evil. You eat souls for subsistence.': '战争贩子效果反转，改为提升士气。骨头取代木材出现，骸骨织物取代胶合板出现，肉取代毛皮出现。冶炼厂中，灵魂取代木材作为燃料。灵魂取代食物出现。',
    'Your citizens exist in a state of bliss, it takes a lot to make them upset. The pompous attitude of your species hinders academic pursuits. Professors are significantly less effective. You are filled with holy energy which helps you smite evil creatures.': '士气低下的产量惩罚减少为正常的 50%。税收抵制不会触发。教授的知识产量 -75%。士兵在地狱维度中战斗评级 +50%。安全指数提升难度 -25%。',
    'You are an artifical lifeform. Additional units must be constructed, population does not grow naturally. You require electricity to keep operational.': '人口不会自然增长，只能通过制造增加，从事科研工作的市民效率 +20%。每位市民需要 0.2MW 电力才能正常运作，但伐木工人、石工、回收者、水晶矿工、矿工、煤矿工人和水泥工人的效率 +16%。',
    'Apex Predator': '掠食者',
    'Armored': '装甲',
    'Befuddle': '迷惑性',
    'Blood Thirst': '嗜血',
    'Blurry': '模糊',
    'Brute': '野蛮',
    'Calm': '冷静',
    'Cannibalize': '同类相食',
    'Chameleon': '变色龙',
    'Claws': '巨爪',
    'Compact': '袖珍',
    'Conniving': '诡计多端',
    'Creative': '创造性',
    'Curious': '好奇',
    'Fiery': '燃烧',
    'Forge': '熔炼',
    'Ghostly': '幽灵',
    'Hivemind': '蜂群思维',
    'Humpback': '驼峰',
    'Hyper': '精力旺盛',
    'Imitation': '仿制',
    'Infectious': '传染',
    'Infiltrator': '渗透者',
    'Intelligent': '智慧',
    'Kindling Kindred': '树木亲和',
    'Lawless': '无法无天',
    'Leathery': '皮肤强韧',
    'Linked': '意识连接',
    'Logical': '逻辑性',
    'Magnificent': '优美',
    'Malnutrition': '营养不良',
    'Merchant': '商人',
    'Musical': '音乐家',
    'Optimistic': '乐观',
    'Pack Mentality': '从众心理',
    'Pack Rat': '仓鼠症',
    'Playful': '贪玩',
    'Rage': '愤怒',
    'Rainbow': '彩虹',
    'Regenerative': '高速愈合',
    'Resourceful': '足智多谋',
    'Revive': '复活',
    'Mimic': '拟态',
    'Slaver': '奴隶贩子',
    'Slow Digestion': '消化缓慢',
    'Smart': '聪明',
    'Sniper': '射手',
    'Spiritual': '崇高',
    'Sticky': '黏液',
    'Studious': '好学',
    'Suction Grip': '吸盘',
    'Terrifying': '可怖',
    'Tough': '坚韧',
    'Toxic': '有毒',
    'Tracker': '追踪者',
    'Tunneler': '挖掘者',
    'Unified': '团结',
    'Angry': '易怒',
    'Arrogant': '傲慢',
    'Atrophy': '萎缩',
    'Autoignition': '自燃',
    'Deconstructor': '解构',
    'Diverse': '多样性',
    'Dumb': '愚笨',
    'Environmentalist': '环保主义',
    'Emotionless': '无情',
    'Fragrant': '芬芳',
    'Frail': '脆弱',
    'Free Spirit': '自由',
    'Gluttony': '暴食',
    'Gnawer': '啮齿',
    'Greedy': '贪婪',
    'Hard of Hearing': '听力障碍',
    'Heavy': '沉重',
    'Hibernator': '冬眠',
    'Hooved': '马蹄',
    'Invertebrate': '无脊椎',
    'Lazy': '懒惰',
    'Mistrustful': '不信任',
    'Nearsighted': '近视',
    'Noble': '清高',
    'Nyctophilia': '嗜夜癖',
    'Paranoid': '多疑',
    'Parasite': '寄生虫',
    'Pathetic': '无力',
    'Pessimistic': '悲观',
    'Puny': '弱小',
    'Pyrophobia': '畏热症',
    'Ravenous': '饕餮',
    'Selenophobia': '恐月症',
    'Skittish': '胆小',
    'Slow': '缓慢',
    'Slow Regen': '低速愈合',
    'Snowy': '雪生生物',
    'Solitary': '孤独',
    'Thalassophobia': '恐水症',
    'Truthful': '诚实',
    'Unorganized': '无组织',
    'You are a very dangerous predator. Hunting and combat effectiveness is increased but armor technology is unusable.': '战斗评级 +30%，狩猎产量 +50%，无法研究护甲。',
    'Your race is naturally armored and thus less likely to be fatally wounded in battle.': '士兵战死数量 -50%，地狱维度巡逻队护甲 +2。',
    'Your natural guile helps you complete spy actions quicker.': '间谍行动时间 -50%。',
    'The scent of blood sends your troops into a frenzy increasing your morale temporarily. You are also immune to the warmonger penalty.': '战斗暂时提升士气，上限为 +20，免疫战争贩子惩罚。',
    'For some reason no one can ever get a good look at you. Spies are less likely to be caught during espionage actions.': '间谍行动更容易成功。勘探者死亡率 -25%。',
    'Your race loves fighting and is easier to recruit for battle.': '雇佣兵价格 -50%，新兵训练速度 +100%。',
    'Your people are very calm, rarely getting agitated by anything.': '修禅可获得产量加成。每个冥想室提供 10 禅冥想空间上限。',
    'You are cannibals and will eat your own kind. Gain the strength of your own by ingesting them.': '您可以建造祭坛，献祭市民可以获得各种加成，加成数值为 15%。',
    'Your species natural affinity for hiding has caused them to be more averse to having a standing army.': '军营士兵上限 -1，战斗评级 +20%。地狱维度巡逻队被攻击的概率 -67%，无法与 [难以捉摸] 特质叠加。',
    'Your race is more effective in combat.': '战斗评级 +25%，计算战役结果时我方战斗评级平均值 +25%。',
    'You are very small, and thus do not need many materials to construct things.': '地面建筑成本蠕变 -0.015，太空建筑成本蠕变 -0.0075。',
    'Your conniving ways get you the best deals in trade.': '市场购买价格 -5%，市场出售价格 +15%。',
    'Your species\' natural creativity leads to faster development of super projects.': 'ARPA项目成本蠕变 -0.005，基础成本 -20%。',
    'Your race has to know what\'s behind every closed door. This thirst for knowledge boosts University effectiveness but often gets citizens into trouble.': '每位市民使大学知识上限 +0.1%。由于好奇心可能引发一些随机事件。',
    'Your skin burns with unholy fire, making you one of the most feared opponents on the battlefield.': '战斗评级 +65%，狩猎产量 +25%。',
    'Your ability to breathe fire removes the fuel requirement to operate smelters.': '冶炼厂无需燃料，产量按照石油加成计算，地热发电厂基础发电量 +2MW。',
    'Your connection to the ethereal helps attract souls.': '猎人食物产量 +50%。灵魂井的食物基础产量 +1.5。灵魂宝石掉率 +15%。',
    'Your citizens are highly ineffectual when working as individuals but gain potency as they work in bigger groups.': '士兵、伐木工人、石工、回收者、水晶矿工、矿工、煤矿工人、水泥工人、教授和科学家的效率随着该项工作的人数而变化。低于 10 人时效率低于正常，高于 10 人时效率高于正常。',
    'Your race loves to hoard money.': '银行资金上限 +20%。',
    'You can go longer periods of time without eating and can haul more basic materials from worksites.': '饿死的阈值 +0.5 （阈值默认为 1.25，如果食物产量≥食物消耗/阈值，则不会有市民饿死）。伐木工人、石工、回收者、水晶矿工、矿工和煤矿工人产量 +20%。',
    'Your race can never sit still and is always doing something.': '游戏速度 +5%。',
    'You are an imitation of another species, you have weaker versions of their attributes as a result.': '您可以获得上次完成智械黎明剧情模式时，所选择种族的相应特质。可以获得的特质为所选择种族的种群特质，以及该种族价值最高的正面主修特质和价值最低的负面主修特质，正面特质级别为 0.5，负面特质级别为 1。',
    'Your race spreads by infecting other creatures and taking over the host body.': '战斗时有机会获得新市民。根据战役规模不同，至多有 2 / 3 / 5 / 10 / 25 名敌军士兵被感染转化为市民。。',
    'You are the ultimate infiltrator, able to break into any secure location and steal valuable secrets.': '培训间谍的花费更低，您可以直接窃取部分研究，但前提是您的知识上限达到了相应研究知识上限的 90%。仙女座星云获取详细信息的侦察舰数量需求 -1。',
    'Your species always leverages the latest advancements in science to its full benefit.': '每有一位教授，就使全局产量 +0.125%，每有一位科学家，就使全局产量 +0.25%。',
    'Your race is averse to cutting down trees for lumber. All lumber costs are removed but other costs are increased.': '木材、胶合板、骨头、骸骨织物等资源都被去除，正常情况下需要这些资源进行建造的建筑改为建筑成本 +5%。',
    'Your disrespect for central authority lets you change government much more frequently.': '改革政府体制的冷却时间 -90%。',
    'Your race has leathery skin, which makes them more weather resistant.': '降低坏天气的士气惩罚。',
    'Your citizens are all linked together which grants you extra computational power.': '每位市民使量子水平 +0.1%。该效果在达到 80% 以后增长大幅放缓。',
    'Your citizens contribute directly to your knowledge cap.': '沃登克里弗塔（或通天塔、法师塔）的基础知识成本 -100。每位市民使知识上限 +25×科学因子 。科学因子的数值为您的科学研究等级与先进技术研究等级之和',
    'You are a magnificent creature of the light. Seekers of the light will often leave you tribute at shrines dedicated to your magnificence.': '您可以建造圣地，圣地的加成与建造时的月相有关。峨眉月提升士气，盈凸月提升金属产量，张弦月提升知识上限，残月提升税收收入，剩余的新月、上弦月、满月、下弦月时提升随机一项。盈凸月提升的金属产量包括铜、铁、铝、钢、钛、铱和精金的产量。',
    'Your race can function while suffering from malnutrition better than most.': '饥饿时全局产量惩罚 -25%。',
    'Your race has an innate gift for haggling.': '市场出售价格 +25%，市场货物交易数量 +10%。',
    'Entertainers are more effective at keeping the masses happy.': '每位艺人额外使士气 +1%。',
    'Your race always tries to look for the best possible outcome.': '士气下限 +10%，工作压力 -10%。',
    'Your race prefers to live in groups.': '第一级住房成本蠕变 +0.03，第二、三级住房成本蠕变 -0.02。',
    'Your species is adept at packing the most stuff into any storage space.': '板条箱和集装箱储量 +10%，所有物资储量上限 +5%。',
    'Your hunters are happy playing in the wild.': '每位猎人使士气 +0.5%，且不产生工作压力。',
    'When wounded your kind rage with power.': '伤兵战斗评级不再下降，反而 +50%，每名伤兵使士兵战斗评级 +1%。',
    'Whenever rainbows appear you get a significant productivity boost.': '雨后的晴天全局产量 +50%。',
    'Your race inherently heals quickly.': '每次治愈伤兵时额外治愈 3 名伤兵。',
    'Your species resourcefulness leads to less waste when crafting.': '锻造物的原料消耗 -12%。',
    'Your soldiers can sometimes revive after being killed. It is much more likely to occur in hot climates.': '士兵战死后有概率复活，炎热天气概率增加，寒冷天气概率降低。特质级别影响复活概率。',
    'You can assume the properties of other genus.': '您可以获得其他种群的种群特质，正面特质级别为 0.5，负面特质级别为 1。',
    'You use anyone you can capture as forced labor, often working them to death.': '您可以通过战斗捕获奴隶，每个奴隶使全局产量 +0.28%。',
    'Your race digests food slowly and thus will not starve as easily.': '饿死的阈值 +0.75 （阈值默认为 1.25，如果食物产量≥食物消耗/阈值，则不会有市民饿死）。',
    'Your race more easily understands new concepts.': '知识成本 -10%。',
    'Your mastery of ranged weaponry makes new weapons more impactful.': '武器升级研究效果 +8%。最终效果将乘上武器升级研究次数。（双层床也视为武器升级研究。）',
    'Your spirituality increases the effectiveness of temples.': '寺庙的全局产量加成效果 +13%。',
    'Your sticky body traps prey reducing food requirements and giving you an edge in combat.': '食物消耗 -20%，战斗评级 +15%。',
    'Your race is more focused when studying than average. Knowledge is gained faster as a result.': '教授知识产量 +0.25。图书馆知识上限 +10%。',
    'Your superior grip boosts all productivity.': '全局产量 +8%。',
    'You are so terrifying that no one will trade with you.': '无法进行贸易，但可以从战利品中获取钛。特质级别影响获取钛的数量。',
    'Your race is tough and can withstand the most gruelling jobs without succumbing to weakness.': '矿工和煤矿工人产量 +25%。',
    'Your species\' natural toxicity makes them resistant to toxic workplaces and thus are more productive in factories.': '工厂的奢侈品、毛皮、合金、聚合物产量 +20%，纳米管、锡烯产量 +8%，水泥工人产量 +30%。',
    'Your race excels at tracking game, and thus produces more from hunting.': '狩猎产量 +20%。',
    'Your species is naturally adept at digging tunnels, which make mine shafts cheaper to produce.': '矿井和煤矿成本蠕变 -0.01。',
    'Your race is united and does not war amongst themselves.': '开局直接达成统一。',
    'Your race is quick to get angry when hungry.': '饥饿时全局产量惩罚 +25%。',
    'The inherent arrogance of your species often leads to you overpaying in negotiations.': '市场购买价格 +10%。',
    'Your race atrophies quicker when not well fed.': '饿死的阈值 -0.15 （阈值默认为 1.25，如果食物产量≥食物消耗/阈值，则不会有市民饿死）。',
    'Your core body temperature causes paper to combust near you, reducing the knowledge bonus from libraries.': '图书馆的知识产量加成 -2%。',
    'You destroy matter to reorder it for your own purposes.': '将资源转化为纳米体。',
    'The diverse nature of your species makes working together as a cohesive military unit more difficult.': '新兵训练时间 +25%。',
    'Your race does not easily understand new concepts.': '知识成本 +5%。',
    'You have no emotions, cold logic dictates your decisions.': '艺人效果 -35%，工作压力 -13%。',
    'You seek balance with nature above all other things.': '水电站取代煤电厂出现，+4MW 电力，无能源消耗。风电站取代石油发电厂出现，+5MW 电力，无能源消耗，有风时额外+2MW 电力。风车 +1.5MW 电力。',
    'You give off a strong odor, which while not unpleasant makes hunting harder.': '狩猎产量 -20%。',
    'Your race is frail and is more likely to die in combat.': '战斗胜利时，士兵战死数量 +1, 战斗失败时，士兵战死数量 +1。',
    'Those forced to conform and hold modern jobs are less happy.': '基础类型以外的工作，也就是有人数上限的工作，产生的工作压力 +50%。',
    'Your species is always hungry and eats extra food.': '食物消耗 +10%。',
    'Your race requires constant gnawing to keep your teeth filed.': '每位市民每秒消耗 0.25 木材。',
    'Your race is greedy and will not willingly part with money, reducing income from taxes.': '税收收入 -12.5%。',
    'Your species has poor hearing and thus lectures are less effective.': '大学的知识上限 -5%。',
    'Your heavy weight requires extra materials to support.': '燃料成本 +10%，部分材料成本 +5%。（石头、水泥和锻铁成本增加）',
    'Your species lowers their metabolic rate during the winter, consuming less energy but also being far less productive.': '冬季的食物消耗 -25%，全局产量 -8%。',
    'You require manufacturing special shoes to expand your population.': '建造住房时需要马蹄铁。',
    'Your lack of a skeletal structure means you can\'t haul away as much loot from battle.': '战利品 -10%。',
    'Your race loves nothing more than a lazy afternoon. Productivity is lost in warm weather as a result.': '炎热时，全局产量 -10%。',
    'Conflicts cause you to lose reputation with rival cities faster.': '战争后双边关系额外 -2%。',
    'Your species is nearsighted and requires bigger font sizes to read.': '图书馆的知识上限 -12%。',
    'Your noble race is immune to corruption and will not implement extreme tax strategies.': '税率被限制在 10% 至 20% 之间。',
    'Your race does not like direct sunlight, they are less productive when it\'s sunny.': '晴天时士气 -5%。多云时士气 +2%。',
    'Your race is paranoid and doesn\'t trust banks.': '银行资金上限 -10%。',
    'Your species is a parasite and must infect host victims to grow.': '人口只在有风时自然增长，开局拥有 2 名士兵。',
    'You are pathetic in combat, the other demons view you as vermin.': '战斗评级 -25%。',
    'Your race gets depressed easily.': '工作压力 +2。',
    'Your race is less effective in combat.': '计算战役结果时我方战斗评级平均值 -15%，战斗评级 -10%。',
    'Your race is afraid of fire and smelters operate slower as a result': '冶炼厂产量 -10%。',
    'You are always starving and consume everything available.': '食物消耗随着食物储量而增加，每个时刻额外消耗 20% 食物，并消耗当前食物储量的 1/3。',
    'Your race prefers moonless nights.': '月相影响全局产量，从满月时全局产量 -10% 到新月时全局产量 +4% 之间变化。',
    'Your race is easily startled and may lose productivity when scared.': '雷雨天士气 -12%。',
    'Your species is slow moving and rarely in a hurry to get anything done.': '游戏速度 -10%。',
    'Your soldiers wounds heal at a reduced rate.': '伤兵治愈速度 -25%。',
    'Your race loves snow so much that they become depressed when there is no snow.': '非雪天时，士气 -2% 至 -5%。',
    'Your race prefers to live alone rather than with others.': '第一级住房成本蠕变 -0.02，第二级住房成本蠕变 +0.02。',
    'You dislike large bodies of water and will not invest in developing the sea.': '无法建造码头。',
    'You are incapable of lying. This makes you inherently bad at some professions.': '银行家效果 -50%。',
    'It takes longer to organize a revolution.': '改革政府体制的冷却时间 +50%。',


    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Science 1, Fearmongers 0": "懂科学，就无需恐惧。",
    "Bioseeded a with a macro sized race (small/compact race inside micro universe)": "在微型宇宙中，使用有 [微型] 特质或 [袖珍] 特质的种族进行播种重置。",
    "Raised your morale to 500%": "将士气提升至 500%。",
    "Increases Spire Mech power by 5%": "尖塔机甲的效率 +5%。",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^(\s*)For Evolve version$/, '$1适用于进化游戏版本'],
    [/^Earned (\d+) Achievements$/, '完成 $1 个成就。'],
    [/^Gain (\d+)x genes from genome mutation and (\d+)% more from auto sequencing$/, '通过基因突变获得的基因数量变为原来的 $1 倍，自动测序获得的基因数量 +$2%'],
    [/^Gain increasing Plasmids from each mutation, caps at \+(\d+) per mutation.$/, '通过基因突变获得的质粒数量提升，上限为 +$1'],
    [/^Craftsmen produce (\d+)% more product from the same amount of raw materials.$/, '工匠产量 +$1%（原料消耗保持不变）'],
    [/^([\d\.]+)% of Plasmids function in the antimatter universe$/, '在反物质宇宙中，可以有总数 $1% 的质粒生效'],
    [/^([\d\.]+)% of Anti-Plasmids function outside the antimatter universe$/, '在反物质宇宙以外的宇宙中，可以有总数 $1% 的反质粒生效'],
    [/^(\d+) Blood Stones$/, '$1 鲜血之石'],
    [/^(\d+) Blood Stones, (\d+) Artifacts$/, '$1 鲜血之石，$2 上古遗物'],
    [/^(\d+) Plasmids$/, '$1 质粒'],
    [/^(\d+) Anti-Plasmids$/, '$1 反质粒'],
    [/^(\d+) Phages$/, '$1 噬菌体'],
    [/^(\d+) Artifact$/, '$1 上古遗物'],
    [/^([\d\.]+)% Complete$/, '完成率：$1%'],
    [/^Standard Universe: (\d+) of (\d+) \($/, '标准宇宙：$1个已获得，共$2个('],
    [/^Heavy Universe: (\d+) of (\d+) \($/, '高引力宇宙：$1个已获得，共$2个('],
    [/^Micro Universe: (\d+) of (\d+) \($/, '微型宇宙：$1个已获得，共$2个('],
    [/^Evil Universe: (\d+) of (\d+) \($/, '邪恶宇宙：$1个已获得，共$2个('],
    [/^Antimatter Universe: (\d+) of (\d+) \($/, '反物质宇宙：$1个已获得，共$2个('],
    [/^Magic Universe: (\d+) of (\d+) \($/, '魔法宇宙：$1个已获得，共$2个('],
    [/^\(([\d\.]+)% Complete$/, '个(完成率：$1%'],
    [/^\(([\d\.]+)% Purchased$/, '个(购买率：$1%'],
]);